<?php
    /**
     * Implements hook_preprocess_HOOK().
     *
     */
      function srijan_preprocess_html(&$variables) {
        $node = \Drupal::request()->attributes->get('node');
        $current_uri = \Drupal::request()->getRequestUri();
        $path_args = explode('/', $current_uri);
        $end_array = end($path_args);
        if ($node) {
          $variables['attributes']['class'][] = 'page-node-' . $end_array;
        }
      }
